#!/bin/bash
##########################################################################################
# Declaração de variáveis e funções
##########################################################################################
BASE_URL()
	{
	echo "coolrom.com/roms/"$VG_URL"/"$LETRA""
	}


DATA_CLEANUP()
{
mkdir data

rm data/*
}

BANNER()
	{
	# Imprime o cabeçalho do programa:
	clear
	echo ''
	echo ' ▄▄·             ▄▄▌  ▄▄▄        • ▌ ▄ ·.'
	echo '▐█ ▌▪▪     ▪     ██•  ▀▄ █·▪     ·██ ▐███▪'
	echo '██ ▄▄ ▄█▀▄  ▄█▀▄ ██▪  ▐▀▀▄  ▄█▀▄ ▐█ ▌▐▌▐█·'
	echo '▐███▌▐█▌.▐▌▐█▌.▐▌▐█▌▐▌▐█•█▌▐█▌.▐▌██ ██▌▐█▌'
	echo '·▀▀▀  ▀█▄▀▪ ▀█▄▀▪.▀▀▀ .▀  ▀ ▀█▄▀▪▀▀  █▪▀▀▀'
	echo '·▄▄▄▄        ▄▄▌ ▐ ▄▌ ▐ ▄ ▄▄▌         ▄▄▄· ·▄▄▄▄  ▄▄▄ .▄▄▄'
	echo '██▪ ██ ▪     ██· █▌▐█•█▌▐███•  ▪     ▐█ ▀█ ██▪ ██ ▀▄.▀·▀▄ █·'
	echo '▐█· ▐█▌ ▄█▀▄ ██▪▐█▐▐▌▐█▐▐▌██▪   ▄█▀▄ ▄█▀▀█ ▐█· ▐█▌▐▀▀▪▄▐▀▀▄'
	echo '██. ██ ▐█▌.▐▌▐█▌██▐█▌██▐█▌▐█▌▐▌▐█▌.▐▌▐█ ▪▐▌██. ██ ▐█▄▄▌▐█•█▌'
	echo '▀▀▀▀▀•  ▀█▄▀▪ ▀▀▀▀ ▀▪▀▀ █▪.▀▀▀  ▀█▄▀▪ ▀  ▀ ▀▀▀▀▀•  ▀▀▀ .▀  ▀'
	echo 'Email: victor.oliveira@gmx.com'

	sleep 3

	
	}

INICIO()
{
ESCOLHA=$(dialog --stdout --menu 'Escolha seu console:' \
	       0 0 15 atari2600 'Atari 2600' \
	atari5200 'Atari 5200' \
	atari7800 'Atari 7800' \
	atarijaguar 'Atari Jaguar' \
	atarilynx 'Atari Lynx' \
	c64 'Commodore 64' \
	cps1 'Capcom CPS1' \
	cps2 'Capcom CPS2' \
	mame 'MAME Arcade' \
	namcosystem22 'Namco System 22' \
	neogeo 'Neo Geo' \
	neogeocd 'Neo Geo CD' \
	neogeopocket 'Neo Geo Pocket' \
	segacd 'Sega CD' \
	dc 'Sega Dreamcast' \
	gamegear 'Sega Game Gear' \
	genesis 'Sega Genesis' \
	mastersystem 'Sega Master System' \
	model2 'Sega Model 2' \
	saturn	'Sega Saturn' \
	psx 'Sony Playstation' \
	ps2 'Sony Playstation 2' \
	psp 'Sony PSP' )

}

BUSCA_LETRA()
	{
	ESCOLHA=$(dialog --stdout --menu 'Busca completa ou alfabetica: ' \
		0 0 0 C "Ordem Alfabetica" \
		      A "Listagem Completa" )

case $ESCOLHA in 
	C) LISTA_JOGOS_ALFABETO
	   ;;
	A) LISTA_JOGOS_TODOS
  	   ;;
esac
	}

LISTA_JOGOS_TODOS()
{

for LETRA in {A..Z} {0..9};
do
        lynx -dump $(BASE_URL)| awk '/[0-9]\/'"$LETRA"'/{print $2}' | grep $VG_URL > data/$LETRA
done


ESCOLHA=$(dialog --stdout --menu 'Selecione seu GAME:' \
	0 0 0 `(cd data && cat $(ls -pa | grep -v / ) && cd ..) | nl`)

BAIXA_ROM

}	

BAIXA_ROM()
	{

	URL=`(cd data && cat $(ls -pa | grep -v / ) && cd ..) | nl | awk '{print $2}'| sed ''"$ESCOLHA"'!d'`	

	# Variáveis
	ROM ()
		{
		curl -sA 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0' "$URL"|grep "tr_download_url"|cut -d \" -f2
		}

	FN ()
		{
		curl -sA 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0' "$URL"| grep "File Name"| sed -e 's/<[^>]*>//g'| cut -c14-
		}
	
	# Mostra algumas informações
	clear
	echo ""
	echo "Link para download:"
	echo $(ROM)
	echo ""
	echo "Nome do arquivo:"
	echo $(FN)
	echo ""
	echo "Iniciando download..."
		
	# Inicia o donwload
	wget -O "$(FN)" "$(ROM)" && \
	echo ""
	echo "*** Download Concluído! ***"
	echo "Arquivo salvo na pasta: $PWD"
	echo "Recomeçando..."
	sleep 3
	exec bash "$0"
	}

##########################################################################################
# Inicio do script
##########################################################################################
BANNER 
DATA_CLEANUP
INICIO

case $ESCOLHA in 
	atari2600)
		VG="Atari 2600"
		VG_URL="atari2600"
		BUSCA_LETRA
		;;
esac
