#!/bin/bash
##########################################################################################
# Declaração de variáveis e funções
##########################################################################################
BASE_URL()
	{
	echo "coolrom.com/roms/"$VG_URL"/"$LETRA""
	}


DATA_CLEANUP()
{
mkdir data

rm data/*
}

BANNER()
	{
	# Imprime o cabeçalho do programa:
	clear
	echo ''
	echo ' ▄▄·             ▄▄▌  ▄▄▄        • ▌ ▄ ·.'
	echo '▐█ ▌▪▪     ▪     ██•  ▀▄ █·▪     ·██ ▐███▪'
	echo '██ ▄▄ ▄█▀▄  ▄█▀▄ ██▪  ▐▀▀▄  ▄█▀▄ ▐█ ▌▐▌▐█·'
	echo '▐███▌▐█▌.▐▌▐█▌.▐▌▐█▌▐▌▐█•█▌▐█▌.▐▌██ ██▌▐█▌'
	echo '·▀▀▀  ▀█▄▀▪ ▀█▄▀▪.▀▀▀ .▀  ▀ ▀█▄▀▪▀▀  █▪▀▀▀'
	echo '·▄▄▄▄        ▄▄▌ ▐ ▄▌ ▐ ▄ ▄▄▌         ▄▄▄· ·▄▄▄▄  ▄▄▄ .▄▄▄'
	echo '██▪ ██ ▪     ██· █▌▐█•█▌▐███•  ▪     ▐█ ▀█ ██▪ ██ ▀▄.▀·▀▄ █·'
	echo '▐█· ▐█▌ ▄█▀▄ ██▪▐█▐▐▌▐█▐▐▌██▪   ▄█▀▄ ▄█▀▀█ ▐█· ▐█▌▐▀▀▪▄▐▀▀▄'
	echo '██. ██ ▐█▌.▐▌▐█▌██▐█▌██▐█▌▐█▌▐▌▐█▌.▐▌▐█ ▪▐▌██. ██ ▐█▄▄▌▐█•█▌'
	echo '▀▀▀▀▀•  ▀█▄▀▪ ▀▀▀▀ ▀▪▀▀ █▪.▀▀▀  ▀█▄▀▪ ▀  ▀ ▀▀▀▀▀•  ▀▀▀ .▀  ▀'
	echo 'Email: victor.oliveira@gmx.com'

	sleep 3

	
	}

INICIO()
{
ESCOLHA=$(dialog --stdout --menu 'Escolha seu console:' \
	       0 0 15 1 'Atari 2600' \
	2 'Atari 5200' \
	3 'Atari 7800' \
	4 'Atari Jaguar' \
	5 'Atari Lynx' \
	6 'Commodore 64' \
	7 'Capcom CPS1' \
	8 'Capcom CPS2' \
	9 'MAME Arcade' \
	10 'Namco System 22' \
	11 'Neo Geo' \
	12 'Neo Geo CD' \
	13 'Neo Geo Pocket' \
	14 'Sega CD' \
	15 'Sega Dreamcast' \
	16 'Sega Game Gear' \
	17 'Sega Genesis' \
	18 'Sega Master System' \
	19 'Sega Model 2' \
	20 'Sega Saturn' \
	21 'Sony Playstation' \
	22 'Sony Playstation 2' \
	23 'Sony PSP' )

}

BUSCA_LETRA()
	{
	ESCOLHA=$(dialog --stdout --menu 'Busca completa ou alfabetica: ' \
		0 0 0 C "Ordem Alfabetica" \
		      A "Listagem Completa" )

case $ESCOLHA in 
	C) LISTA_JOGOS_ALFABETO
	   ;;
	A) LISTA_JOGOS_TODOS
  	   ;;
esac
	}

LISTA_JOGOS_TODOS()
{

for LETRA in {A..Z} {0..9};
do
        lynx -dump $(BASE_URL)| awk '/[0-9]\/'"$LETRA"'/{print $2}' | grep $VG_URL > data/$LETRA
done


ESCOLHA=$(dialog --stdout --menu 'Selecione seu GAME:' \
	0 0 0 `(cd data && cat $(ls -pa | grep -v / ) && cd ..) | nl`)

BAIXA_ROM

}	

BAIXA_ROM()
	{

	URL=`(cd data && cat $(ls -pa | grep -v / ) && cd ..) | nl | awk '{print $2}'| sed ''"$ESCOLHA"'!d'`	

	# Variáveis
	ROM ()
		{
		curl -sA 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0' "$URL"|grep "tr_download_url"|cut -d \" -f2
		}

	FN ()
		{
		curl -sA 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0' "$URL"| grep "File Name"| sed -e 's/<[^>]*>//g'| cut -c14-
		}
	
	# Mostra algumas informações
	clear
	echo ""
	echo "Link para download:"
	echo $(ROM)
	echo ""
	echo "Nome do arquivo:"
	echo $(FN)
	echo ""
	echo "Iniciando download..."
		
	# Inicia o donwload
	wget -O "$(FN)" "$(ROM)" && \
	echo ""
	echo "*** Download Concluído! ***"
	echo "Arquivo salvo na pasta: $PWD"
	echo "Recomeçando..."
	sleep 3
	exec bash "$0"
	}

##########################################################################################
# Inicio do script
##########################################################################################
BANNER 
DATA_CLEANUP
INICIO

case $ESCOLHA in 
	1)
		VG="Atari 2600"
		VG_URL="atari2600"
		BUSCA_LETRA
		;;

	2)
		VG="Atari 5200"
		VG_URL="atari5200"
		BUSCA_LETRA
		;;

	3)
		VG="Atari 7800"
		VG_URL="atari7800"
		BUSCA_LETRA
		;;
	
	4)
		VG="Atari Jaguar"
		VG_URL="atarijaguar"
		BUSCA_LETRA
		;;

	5)
		VG="Atari Lynx"
		VG_URL="atarilynx"
		BUSCA_LETRA
		;;
	
	6)	VG="Commodore 64"
		VG_URL="c64"
		BUSCA_LETRA
		;;

	7)	VG="Capcom CPS1"
		VG_URL="cps1"
		BUSCA_LETRA
		;;
	
	8)	VG="Capcom CPS2"
		VG_URL="cps2"
		BUSCA_LETRA
		;;

	9)	VG="MAME Arcade"
		VG_URL="mame"
		BUSCA_LETRA
		;;
	
	10)	VG="Namco System 32"
		VG_URL="namcosystem32"
		BUSCA_LETRA
		;;
	
	11)	VG="Neo Geo"
		VG_URL="neogeo"
		BUSCA_LETRA
		;;
	
	12)	VG="Neo Geo CD"
		VG_URL="neogeocd"
		BUSCA_LETRA
		;;
	
	13)	VG="Neo Geo Pocket"
		VG_URL="neogeopocket"
		BUSCA_LETRA
		;;
	
	14)	VG="Sega CD"
		VG_URL="segacd"
		BUSCA_LETRA
		;;
	
	15)	VG="Sega Dreamcast"
		VG_URL="dc"
		BUSCA_LETRA
		;;
	
	16)	VG="Sega Game Gear"
		VG_URL="gamegear"
		BUSCA_LETRA
		;;
	
	17)	VG="Sega Genesis"
		VG_URL="genesis"
		BUSCA_LETRA
		;;
	
	18)	VG="Sega Master System"
		VG_URL="mastersystem"
		BUSCA_LETRA
		;;
	
	19) 	VG="Sega Model 2"
		VG_URL="model2"
		BUSCA_LETRA
		;;
	
	20) 	VG="Sega Saturn"
		VG_URL="saturn"
		BUSCA_LETRA
		;;

	21)	VG="Sony Playstation"
		VG_URL="psx"
		BUSCA_LETRA
		;;

	22) 	VG="Sony Playstation 2"
		VG_URL="ps2"
		BUSCA_LETRA
		;;

	23)	VG="Sony PSP"
		VG_URL="psp"
		BUSCA_LETRA
		;;
	
esac
